name: construction_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.3.10"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  intl: ^0.18.0
  logger: ^1.1.0
  package_info_plus: ^4.0.1
  permission_handler: ^10.0.0
  retrofit: ^4.0.1
  table_calendar: ^3.0.9
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.4
  uuid: ^3.0.6
#
#dependency_overrides:
#  analyzer: ">=4.3.1 <5.0.0"

dev_dependencies:
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  json_serializable: '>4.4.0'
  retrofit_generator: ^7.0.1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Construction Mobile Dev"
      android:
        applicationId: "construction.mobile.app.com.jp.dev"
      ios:
        bundleId: "construction.mobile.app.com.jp.dev"

    staging:
      app:
        name: "Construction Mobile Stg"
      android:
        applicationId: "construction.mobile.app.com.jp.stg"
      ios:
        bundleId: "construction.mobile.app.com.jp.stg"

    production:
      app:
        name: "Construction Mobile Pro"
      android:
        applicationId: "construction.mobile.app.com.jp.pro"
      ios:
        bundleId: "construction.mobile.app.com.jp.pro"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true

  fonts:
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SF-ProText-Regular.ttf

  assets:
    - assets/
